/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	openapi "myapi/go"
	"myapi/myapi"
	"net/http"
)

func main() {
	log.Printf("Server started")

	memoryStore := new(myapi.MemoryItemStore)
	memoryStore.CreateItem("this is a test")
	memoryStore.CreateItem("and this is another test")

	ItemAPIService := myapi.NewItemAPIService(memoryStore)
	ItemAPIController := openapi.NewDefaultApiController(ItemAPIService)

	router := openapi.NewRouter(ItemAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
