openapi: 3.0.3
info:
  title: Pegarata API
  description: Pegarata API allows you to interact with your shopping list
  version: 0.1.0
servers:
  - url: http://127.0.0.1:8080
paths:
  /items:
    get:
      summary: Returns a list of items
      description: Returns a list of items
      responses:
        '200':    # status code
          description: A JSON array of items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfPersistedItems'
            application/yaml:
              schema:
                $ref: '#/components/schemas/ArrayOfPersistedItems'
    post:
      summary: Creates an extra item
      description: Creates an extra item      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':    # status code
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistedItem'
            application/yaml:
              schema:
                $ref: '#/components/schemas/PersistedItem'
  /items/{itemId}:
    delete:
      summary: Removes an item from the list
      description: Removes an item from the list      
      parameters:
        - name: itemId
          in: path
          description: None
          required: true
          schema:
            #type: integer
            type: string
            format: uuid
      responses:
        '200':    # status code
          description: Deleted
        '404':
          description: Not Found

  /ping:
    get:
      summary: Heartbeat
      description: Checks the health of the API
      responses:
        '200':
          description: A status message repesenting the health of the API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeartBeatResponse'
components:
  schemas:
    Item:
      type: object
      properties:
        name:
          type: string
          maxLength: 24
      example:
        name: chorizo
    PersistedItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      example:
        id: d5fa7a5e-41a2-44d2-bede-00130f7569b4
        name: chorizo
    ArrayOfPersistedItems:
      type: array
      items:
        $ref: '#/components/schemas/PersistedItem'          
    HeartBeatResponse:
      type: object
      properties:
        status:
          type: string
          enum: [OK, FAILURE]
        message:
          type: string
      example:
        status: OK
        name: All OK!
